graph TD
  openalex_works_20260225["openalex_works_20260225<br/>rows: 1000"]
  openalex_works_20260225__authorships["openalex_works_20260225__authorships<br/>rows: 1000"]
  openalex_works_20260225__best_oa_location__source__host_organization_lineage["openalex_works_20260225__best_oa_location__source__host_organization_lineage<br/>rows: 1000"]
  openalex_works_20260225__best_oa_location__source__host_organization_lineage_names["openalex_works_20260225__best_oa_location__source__host_organization_lineage_names<br/>rows: 982"]
  openalex_works_20260225__best_oa_location__source__issn["openalex_works_20260225__best_oa_location__source__issn<br/>rows: 1000"]
  openalex_works_20260225__concepts["openalex_works_20260225__concepts<br/>rows: 1000"]
  openalex_works_20260225__corresponding_author_ids["openalex_works_20260225__corresponding_author_ids<br/>rows: 1000"]
  openalex_works_20260225__corresponding_institution_ids["openalex_works_20260225__corresponding_institution_ids<br/>rows: 463"]
  openalex_works_20260225__counts_by_year["openalex_works_20260225__counts_by_year<br/>rows: 1000"]
  openalex_works_20260225__excepted__abstract_inverted_index["openalex_works_20260225__excepted__abstract_inverted_index<br/>rows: 1000"]
  openalex_works_20260225__funders["openalex_works_20260225__funders<br/>rows: 89"]
  openalex_works_20260225__indexed_in["openalex_works_20260225__indexed_in<br/>rows: 754"]
  openalex_works_20260225__keywords["openalex_works_20260225__keywords<br/>rows: 1000"]
  openalex_works_20260225__locations["openalex_works_20260225__locations<br/>rows: 1000"]
  openalex_works_20260225__mesh["openalex_works_20260225__mesh<br/>rows: 1000"]
  openalex_works_20260225__primary_location__source__host_organization_lineage["openalex_works_20260225__primary_location__source__host_organization_lineage<br/>rows: 1000"]
  openalex_works_20260225__primary_location__source__host_organization_lineage_names["openalex_works_20260225__primary_location__source__host_organization_lineage_names<br/>rows: 1000"]
  openalex_works_20260225__primary_location__source__issn["openalex_works_20260225__primary_location__source__issn<br/>rows: 1000"]
  openalex_works_20260225__referenced_works["openalex_works_20260225__referenced_works<br/>rows: 1000"]
  openalex_works_20260225__related_works["openalex_works_20260225__related_works<br/>rows: 1000"]
  openalex_works_20260225__sustainable_development_goals["openalex_works_20260225__sustainable_development_goals<br/>rows: 1000"]
  openalex_works_20260225__topics["openalex_works_20260225__topics<br/>rows: 1000"]
  openalex_works_20260225 -->|authorships| openalex_works_20260225__authorships
  openalex_works_20260225 -->|best_oa_location__source__host_organization_lineage| openalex_works_20260225__best_oa_location__source__host_organization_lineage
  openalex_works_20260225 -->|best_oa_location__source__host_organization_lineage_names| openalex_works_20260225__best_oa_location__source__host_organization_lineage_names
  openalex_works_20260225 -->|best_oa_location__source__issn| openalex_works_20260225__best_oa_location__source__issn
  openalex_works_20260225 -->|concepts| openalex_works_20260225__concepts
  openalex_works_20260225 -->|corresponding_author_ids| openalex_works_20260225__corresponding_author_ids
  openalex_works_20260225 -->|corresponding_institution_ids| openalex_works_20260225__corresponding_institution_ids
  openalex_works_20260225 -->|counts_by_year| openalex_works_20260225__counts_by_year
  openalex_works_20260225 -->|excepted__abstract_inverted_index| openalex_works_20260225__excepted__abstract_inverted_index
  openalex_works_20260225 -->|funders| openalex_works_20260225__funders
  openalex_works_20260225 -->|indexed_in| openalex_works_20260225__indexed_in
  openalex_works_20260225 -->|keywords| openalex_works_20260225__keywords
  openalex_works_20260225 -->|locations| openalex_works_20260225__locations
  openalex_works_20260225 -->|mesh| openalex_works_20260225__mesh
  openalex_works_20260225 -->|primary_location__source__host_organization_lineage| openalex_works_20260225__primary_location__source__host_organization_lineage
  openalex_works_20260225 -->|primary_location__source__host_organization_lineage_names| openalex_works_20260225__primary_location__source__host_organization_lineage_names
  openalex_works_20260225 -->|primary_location__source__issn| openalex_works_20260225__primary_location__source__issn
  openalex_works_20260225 -->|referenced_works| openalex_works_20260225__referenced_works
  openalex_works_20260225 -->|related_works| openalex_works_20260225__related_works
  openalex_works_20260225 -->|sustainable_development_goals| openalex_works_20260225__sustainable_development_goals
  openalex_works_20260225 -->|topics| openalex_works_20260225__topics
