graph TD
  WoS_Sample__MN["WoS_Sample__MN<br/>rows: n/a"]
  WoS_Sample__MN_SUB__dynamic_data__citation_related__SDG__sdg_category["WoS_Sample__MN-SUB__dynamic_data__citation_related__SDG__sdg_category<br/>rows: n/a"]
  WoS_Sample__MN_SUB__dynamic_data__citation_related__citation_topics__subj_group__subject["WoS_Sample__MN-SUB__dynamic_data__citation_related__citation_topics__subj-group__subject<br/>rows: n/a"]
  WoS_Sample__MN_SUB__dynamic_data__cluster_related__identifiers__identifier["WoS_Sample__MN-SUB__dynamic_data__cluster_related__identifiers__identifier<br/>rows: n/a"]
  WoS_Sample__MN_SUB__dynamic_data__ic_related__oases__oas["WoS_Sample__MN-SUB__dynamic_data__ic_related__oases__oas<br/>rows: n/a"]
  WoS_Sample__MN_SUB__static_data__contributors__contributor["WoS_Sample__MN-SUB__static_data__contributors__contributor<br/>rows: n/a"]
  WoS_Sample__MN_SUB__static_data__fullrecord_metadata__addresses__address_name["WoS_Sample__MN-SUB__static_data__fullrecord_metadata__addresses__address_name<br/>rows: n/a"]
  WoS_Sample__MN_SUB__static_data__fullrecord_metadata__category_info__headings__heading["WoS_Sample__MN-SUB__static_data__fullrecord_metadata__category_info__headings__heading<br/>rows: n/a"]
  WoS_Sample__MN_SUB__static_data__fullrecord_metadata__category_info__subheadings__subheading["WoS_Sample__MN-SUB__static_data__fullrecord_metadata__category_info__subheadings__subheading<br/>rows: n/a"]
  WoS_Sample__MN_SUB__static_data__fullrecord_metadata__category_info__subjects__subject["WoS_Sample__MN-SUB__static_data__fullrecord_metadata__category_info__subjects__subject<br/>rows: n/a"]
  WoS_Sample__MN_SUB__static_data__fullrecord_metadata__fund_ack__grants__grant["WoS_Sample__MN-SUB__static_data__fullrecord_metadata__fund_ack__grants__grant<br/>rows: n/a"]
  WoS_Sample__MN_SUB__static_data__fullrecord_metadata__keywords__keyword["WoS_Sample__MN-SUB__static_data__fullrecord_metadata__keywords__keyword<br/>rows: n/a"]
  WoS_Sample__MN_SUB__static_data__fullrecord_metadata__normalized_doctypes__doctype["WoS_Sample__MN-SUB__static_data__fullrecord_metadata__normalized_doctypes__doctype<br/>rows: n/a"]
  WoS_Sample__MN_SUB__static_data__fullrecord_metadata__references__reference["WoS_Sample__MN-SUB__static_data__fullrecord_metadata__references__reference<br/>rows: n/a"]
  WoS_Sample__MN_SUB__static_data__fullrecord_metadata__reprint_addresses__address_name["WoS_Sample__MN-SUB__static_data__fullrecord_metadata__reprint_addresses__address_name<br/>rows: n/a"]
  WoS_Sample__MN_SUB__static_data__item__book_desc["WoS_Sample__MN-SUB__static_data__item__book_desc<br/>rows: n/a"]
  WoS_Sample__MN_SUB__static_data__item__keywords_plus__keyword["WoS_Sample__MN-SUB__static_data__item__keywords_plus__keyword<br/>rows: n/a"]
  WoS_Sample__MN_SUB__static_data__item__reviewed_work__rw_authors__rw_author["WoS_Sample__MN-SUB__static_data__item__reviewed_work__rw_authors__rw_author<br/>rows: n/a"]
  WoS_Sample__MN_SUB__static_data__summary__EWUID__edition["WoS_Sample__MN-SUB__static_data__summary__EWUID__edition<br/>rows: n/a"]
  WoS_Sample__MN_SUB__static_data__summary__conferences__conference__sponsors__sponsor["WoS_Sample__MN-SUB__static_data__summary__conferences__conference__sponsors__sponsor<br/>rows: n/a"]
  WoS_Sample__MN_SUB__static_data__summary__doctypes__doctype["WoS_Sample__MN-SUB__static_data__summary__doctypes__doctype<br/>rows: n/a"]
  WoS_Sample__MN_SUB__static_data__summary__names__name["WoS_Sample__MN-SUB__static_data__summary__names__name<br/>rows: n/a"]
  WoS_Sample__MN_SUB__static_data__summary__titles__title["WoS_Sample__MN-SUB__static_data__summary__titles__title<br/>rows: n/a"]
  WoS_Sample__MN -->|dynamic_data__citation_related__SDG__sdg_category| WoS_Sample__MN_SUB__dynamic_data__citation_related__SDG__sdg_category
  WoS_Sample__MN -->|dynamic_data__citation_related__citation_topics__subj-group__subject| WoS_Sample__MN_SUB__dynamic_data__citation_related__citation_topics__subj_group__subject
  WoS_Sample__MN -->|dynamic_data__cluster_related__identifiers__identifier| WoS_Sample__MN_SUB__dynamic_data__cluster_related__identifiers__identifier
  WoS_Sample__MN -->|dynamic_data__ic_related__oases__oas| WoS_Sample__MN_SUB__dynamic_data__ic_related__oases__oas
  WoS_Sample__MN -->|static_data__contributors__contributor| WoS_Sample__MN_SUB__static_data__contributors__contributor
  WoS_Sample__MN -->|static_data__fullrecord_metadata__addresses__address_name| WoS_Sample__MN_SUB__static_data__fullrecord_metadata__addresses__address_name
  WoS_Sample__MN -->|static_data__fullrecord_metadata__category_info__headings__heading| WoS_Sample__MN_SUB__static_data__fullrecord_metadata__category_info__headings__heading
  WoS_Sample__MN -->|static_data__fullrecord_metadata__category_info__subheadings__subheading| WoS_Sample__MN_SUB__static_data__fullrecord_metadata__category_info__subheadings__subheading
  WoS_Sample__MN -->|static_data__fullrecord_metadata__category_info__subjects__subject| WoS_Sample__MN_SUB__static_data__fullrecord_metadata__category_info__subjects__subject
  WoS_Sample__MN -->|static_data__fullrecord_metadata__fund_ack__grants__grant| WoS_Sample__MN_SUB__static_data__fullrecord_metadata__fund_ack__grants__grant
  WoS_Sample__MN -->|static_data__fullrecord_metadata__keywords__keyword| WoS_Sample__MN_SUB__static_data__fullrecord_metadata__keywords__keyword
  WoS_Sample__MN -->|static_data__fullrecord_metadata__normalized_doctypes__doctype| WoS_Sample__MN_SUB__static_data__fullrecord_metadata__normalized_doctypes__doctype
  WoS_Sample__MN -->|static_data__fullrecord_metadata__references__reference| WoS_Sample__MN_SUB__static_data__fullrecord_metadata__references__reference
  WoS_Sample__MN -->|static_data__fullrecord_metadata__reprint_addresses__address_name| WoS_Sample__MN_SUB__static_data__fullrecord_metadata__reprint_addresses__address_name
  WoS_Sample__MN -->|static_data__item__book_desc| WoS_Sample__MN_SUB__static_data__item__book_desc
  WoS_Sample__MN -->|static_data__item__keywords_plus__keyword| WoS_Sample__MN_SUB__static_data__item__keywords_plus__keyword
  WoS_Sample__MN -->|static_data__item__reviewed_work__rw_authors__rw_author| WoS_Sample__MN_SUB__static_data__item__reviewed_work__rw_authors__rw_author
  WoS_Sample__MN -->|static_data__summary__EWUID__edition| WoS_Sample__MN_SUB__static_data__summary__EWUID__edition
  WoS_Sample__MN -->|static_data__summary__conferences__conference__sponsors__sponsor| WoS_Sample__MN_SUB__static_data__summary__conferences__conference__sponsors__sponsor
  WoS_Sample__MN -->|static_data__summary__doctypes__doctype| WoS_Sample__MN_SUB__static_data__summary__doctypes__doctype
  WoS_Sample__MN -->|static_data__summary__names__name| WoS_Sample__MN_SUB__static_data__summary__names__name
  WoS_Sample__MN -->|static_data__summary__titles__title| WoS_Sample__MN_SUB__static_data__summary__titles__title
